import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const regular = localFont({
  src: "./fonts/CookieRun Regular.ttf",
  variable: "--font-regular",
});
const bold = localFont({
  src: "./fonts/CookieRun Bold.ttf",
  variable: "--font-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={regular.className}>
      <body className={bold.variable}>{children}</body>
    </html>
  );
}
